# Generated by Django 5.0.2 on 2024-06-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='model',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
