# Generated by Django 5.0.2 on 2024-06-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_size_alter_footwear_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sumTotal',
        ),
    ]
