# Generated by Django 5.0.2 on 2024-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_options_remove_order_footwear'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='footwear',
            field=models.ManyToManyField(to='shop.footwear'),
        ),
    ]
