# Generated by Django 5.0.2 on 2024-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_footwear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
